Repository team-xquare/v1-point-service, pull requests merged in 2023-03, with the labels that each got.

#38 상벌점 내역 조회-학생 상벌점 현황 response 추가
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/PointHistoryApi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/dto/response/PointHistoryListStudentResponse.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointHistoryApiImpl.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/exception/UserExistException.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointHandler.kt
Labels: 기능 추가

#41 🔀 :: (#40) 자잘한 에러 수정
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/PointHistory.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointApiImpl.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointHistoryApiImpl.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/PointHistoryEntity.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/repository/PointHistoryRepository.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointHandler.kt
  point-infrastructure/src/main/resources/META-INF/persistence.xml
Labels: 리팩토링, 버그

#42 🔀 :: (#28) 특정 학생 다벌점 교육 완료
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/PointStatus.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/PointHistoryApi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointHistoryApiImpl.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/exception/UserPenaltyExistException.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointHandler.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointRouter.kt
Labels: 기능 추가

#43 🔀 :: (#29) 상벌점 현황 엑셀 다운로드
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/PointHistoryApi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/dto/response/ExportUserPointStatusResponse.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/dto/response/PointHistoryExcelElement.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/dto/response/UserResponse.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointHistoryApiImpl.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/exception/UserRequsetFailedException.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/ExcelSpi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/PointHistoryRepositorySpi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/PointStatusRepositorySpi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/UserSpi.kt
  point-infrastructure/build.gradle.kts
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/repository/PointHistoryRepository.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/repository/PointStatusRepository.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointHandler.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointRouter.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/dto/DomainUserResponse.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/spi/ExcelSpiImpl.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/spi/UserSpiImpl.kt
Labels: 기능 추가

#44 🔀 :: (#27) 학생 상벌점 상태 조회 API
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/PointApi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/dto/response/PointStudentStatusElement.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/dto/response/PointStudentStatusResponse.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointApiImpl.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/exception/PointStatusNotFoundException.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/PointStatusRepositorySpi.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/repository/PointStatusRepository.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointHandler.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/router/PointRouter.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/spi/UserSpiImpl.kt
Labels: 기능 추가

#46 🔀 :: (#45) 벌점봉사 완료 로직 수정
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointHistoryApiImpl.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/PointHistoryRepositorySpi.kt
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/spi/PointRepositorySpi.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/repository/PointHistoryRepository.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/entity/repository/PointRepository.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/spi/ExcelSpiImpl.kt
Labels: 기능 추가

#50 🔀 :: (#49) 사감선생님 요구사항 반영
  point-domain/src/main/kotlin/com/xquare/v1servicepoint/point/api/impl/PointHistoryApiImpl.kt
  point-infrastructure/src/main/kotlin/com/xquare/v1servicepoint/point/spi/ExcelSpiImpl.kt
Labels: 리팩토링
